### PR TITLE
fix(redux): add missing index.js

### PR DESCRIPTION
**Pull request by levithomason**

### CODE REVIEW

**Comment by dvdzkwsk** [comment]
Should there then be a root `index.js` file as well? 👻, not needed just yet, but would follow the paradigm.

**Comment by levithomason** [comment]
It is built from `src/index.js` since `/src` is built to the root.  Hence ignoring it in `.gitignore`.

Though, I think we're going about this backward.  We're building to root, then ignoring everything built in root, then cleaning up everything built to root.  Instead, I think we should just copy the package.json to a `/dist` directory and publish that.  This way, we don't have to manage all the ignore/cleanup code, error prone.

Thoughts?

**Comment by levithomason** [comment]
I'll update this PR with that workflow for feedback.

**Comment by levithomason** [comment]
There we go, way more sane.  Now there is no need for special ignore, post publish clean up, package files array, nor special readme release instructions.

**Comment by dvdzkwsk** [comment]
👻 much betta

**Pull request merged**
